//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hummingbird.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hummingbird.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _1427799497_61706 {
            get {
                object obj = ResourceManager.GetObject("_1427799497_61706", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;s:Header&gt;&lt;RequestServerVersion Version=&quot;Exchange2015&quot; xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;/&gt;&lt;/s:Header&gt;&lt;s:Body&gt;&lt;ValidateUnifiedGroupAlias xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot;&gt;&lt;Alias&gt;##GROUPID##&lt;/Alias&gt;&lt;/ValidateUnifiedGroupAlias&gt;&lt;/s:Body&gt;&lt;/s:Envelope&gt;.
        /// </summary>
        internal static string AliasValidationPOST {
            get {
                return ResourceManager.GetString("AliasValidationPOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Checkmark {
            get {
                object obj = ResourceManager.GetObject("Checkmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;s:Header&gt;
        ///    &lt;RequestServerVersion Version=&quot;Exchange2015&quot; xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;/&gt;
        ///    &lt;MailboxCulture xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;&gt;en-US&lt;/MailboxCulture&gt;
        ///  &lt;/s:Header&gt;
        ///  &lt;s:Body&gt;
        ///    &lt;RemoveUnifiedGroup xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot;&gt;
        ///      &lt;GroupIdentity xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeleteGroupPOST {
            get {
                return ResourceManager.GetString("DeleteGroupPOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Deny {
            get {
                object obj = ResourceManager.GetObject("Deny", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to add members to the group while there are no members in the list..
        /// </summary>
        internal static string ExchangeRequestAddMembersWithoutMembers {
            get {
                return ResourceManager.GetString("ExchangeRequestAddMembersWithoutMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;s:Header&gt;
        ///    &lt;RequestServerVersion Version=&quot;Exchange2015&quot; xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;/&gt;
        ///  &lt;/s:Header&gt;
        ///  &lt;s:Body&gt;
        ///    &lt;GetUnifiedGroupMembers xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot;&gt;
        ///      &lt;GroupIdentity xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;&gt;
        ///        &lt;Type&gt;SmtpAddress&lt;/Type&gt;
        ///        &lt;Value&gt;##GROUP_SMTP_ADDRESS##&lt;/Value&gt;
        ///      &lt;/GroupIdent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMembersPOST {
            get {
                return ResourceManager.GetString("GetMembersPOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;s:Header&gt;
        ///    &lt;RequestServerVersion Version=&quot;Exchange2015&quot; xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;/&gt;
        ///  &lt;/s:Header&gt;
        ///  &lt;s:Body&gt;
        ///    &lt;GetUnifiedGroupMembers xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot;&gt;
        ///      &lt;GroupIdentity xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;&gt;
        ///        &lt;Type&gt;SmtpAddress&lt;/Type&gt;
        ///        &lt;Value&gt;##GROUP_SMTP_ADDRESS##&lt;/Value&gt;
        ///      &lt;/GroupIdent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetUnifiedGroupsPOST {
            get {
                return ResourceManager.GetString("GetUnifiedGroupsPOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;s:Header&gt;&lt;RequestServerVersion Version=&quot;Exchange2015&quot; xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;/&gt;&lt;/s:Header&gt;&lt;s:Body&gt;&lt;CreateUnifiedGroup xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot;&gt;&lt;Name&gt;##GROUPID##&lt;/Name&gt;&lt;Alias&gt;##GROUPID##&lt;/Alias&gt;&lt;AccessType xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;&gt;Public&lt;/AccessType&gt;&lt;Description/&gt;&lt;AutoSubscribeNewMembers&gt;true&lt;/AutoSubscribeNewMembers&gt;&lt;C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupCreationPOST {
            get {
                return ResourceManager.GetString("GroupCreationPOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;s:Header&gt;
        ///    &lt;RequestServerVersion Version=&quot;Exchange2015&quot; xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;/&gt;
        ///  &lt;/s:Header&gt;
        ///  &lt;s:Body&gt;
        ///    &lt;SetUnifiedGroupMembershipState xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot;&gt;
        ///      &lt;GroupIdentity xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;&gt;
        ///        &lt;Type&gt;SmtpAddress&lt;/Type&gt;
        ///        &lt;Value&gt;##GROUP_SMTP_ADDRESS##&lt;/Value&gt;
        ///      &lt;/Gr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SetUnifiedGroupMembersPOST {
            get {
                return ResourceManager.GetString("SetUnifiedGroupMembersPOST", resourceCulture);
            }
        }
    }
}
